### PR TITLE
Bump version to v0.15.1

### PR DESCRIPTION
**Pull request by NastuzziSamy**

### CODE REVIEW

**Comment by Ouack23** [comment]
This PR seems to fix the following bug : 
```
$sudo -u http ./occ app:check-code files_rightclick

Invalid appinfo.xml file found: Element 'licence': [facet 'enumeration'] The value 'AGPL' is not an element of the set {'agpl', 'mpl', 'apache'}.
Invalid appinfo.xml file found: Element 'licence': 'AGPL' is not a valid value of the atomic type 'licence'.
Invalid appinfo.xml file found: Element 'licence': Warning: No precomputed value available, the value was either invalid or something strange happend.
Invalid appinfo.xml file found: Element 'repository': This element is not expected. Expected is one of ( discussion, bugs ).
App is not compliant
```

Please merge it :)

**Comment by jancborchardt** [comment]
@NastuzziSamy this seems to have conflicts with master, could you resolve?

Also cc @Luticus @JoeatMJ @gschbro could you review as this seems to fix issues you reported? :)

**Comment by juliushaertl** [comment]
@NastuzziSamy It seems you released this version to the app store already? Aparently this breaks the update to 18 beta1 since the version from the app store is installed besides the shipped version when the default app folder is not writable. Since the app is shipped it should not be release to the app store anymore. :wink: 

Do you have some time to get this pr merged?

**Comment by jancborchardt** [comment]
@rullzer this might need some help from your side (or someone else capable) especially since this breaks upgrade and Julius is on vacation this week? :)

**Comment by rullzer** [comment]
So the reason it breaks is because 0.15.1 is later than 0.15.0 but is not compatible with 18 but it is shipped. Let me rebase this and merge it.

Then propose a 0.15.2 with 18 support that you can release.

**Pull request merged**
