### PR TITLE
Bump version to 0.15.0 and fix multiple issues + add translations

### PR DESCRIPTION
**Pull request by NastuzziSamy**

### CODE REVIEW

**Comment by NastuzziSamy** [comment]
As I did not release any version since a while, I just released the v0.15.0 considering this PR.

**Comment by jancborchardt** [comment]
Seems good, doing a release with the past changes. cc @rullzer for review too cause it includes changes from you.

**Comment by NastuzziSamy** [comment]
Closing this PR, as I am releasing the v0.15.1 update

**Comment by juliushaertl** [comment]
A release shouldn't be needed as we bundle the app now with the Nextcloud release. In the past this has caused issues with integrity check and on docker setups that don't have a writable default app directory iirc.

**Pull request closed without merging**
